name: fw_stream_with_value
description: A package that handles a stream with the latest value.
version: 0.1.0
homepage: https://futurware.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
