name: fw_stream_with_value
description: A package that handles a stream with the latest value.
version: 0.0.2
author: FutureWare LLC
homepage: https://futurware.dev
# TODO: delete before publishing.
# Packages that use this package before publishing complain.
# https://stackoverflow.com/questions/64660407/
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
